import type { Lesson } from '../features/lessons/types'

export const lessons: Lesson[] = [
  {
    id: 'react-intro',
    slug: 'react-intro',
    title: 'React는 무엇인가',
    section: 'React 시작하기',
    order: 1,
    level: 'beginner',
    estimatedMinutes: 10,
    summary: 'React가 UI를 컴포넌트 단위로 만드는 JavaScript 라이브러리라는 점을 이해합니다.',
    objectives: ['React의 역할을 설명할 수 있다.', '컴포넌트 기반 UI의 장점을 말할 수 있다.'],
    body: ['React는 사용자 인터페이스를 작은 컴포넌트로 나누어 조합하는 라이브러리입니다.', 'React Quest는 ko.react.dev 공식 문서를 더 잘 읽기 위한 실습형 가이드입니다.'],
    officialDocs: [{ title: 'Quick Start', url: 'https://ko.react.dev/learn' }],
    tags: ['react', 'quick-start'],
    prerequisites: [],
  },
  {
    id: 'first-component',
    slug: 'first-component',
    title: '컴포넌트 만들기',
    section: 'UI 표현하기',
    order: 2,
    level: 'beginner',
    estimatedMinutes: 15,
    summary: '컴포넌트를 함수로 정의하고 다른 컴포넌트와 조합합니다.',
    objectives: ['컴포넌트를 함수로 만들 수 있다.', '컴포넌트를 재사용할 수 있다.'],
    body: ['컴포넌트는 UI 일부를 반환하는 JavaScript 함수입니다.', '이름은 대문자로 시작하고 JSX를 반환합니다.'],
    officialDocs: [{ title: '첫 번째 컴포넌트', url: 'https://ko.react.dev/learn/your-first-component' }],
    tags: ['component'],
    prerequisites: ['react-intro'],
  },
  {
    id: 'jsx-basics',
    slug: 'jsx-basics',
    title: 'JSX 이해하기',
    section: 'UI 표현하기',
    order: 3,
    level: 'beginner',
    estimatedMinutes: 15,
    summary: 'JSX로 JavaScript 안에서 UI 구조를 표현합니다.',
    objectives: ['JSX가 무엇인지 설명할 수 있다.', '하나의 부모 요소 규칙을 이해한다.'],
    body: ['JSX는 JavaScript를 확장한 문법입니다.', '컴포넌트는 하나의 JSX 트리를 반환해야 하므로 Fragment를 자주 사용합니다.'],
    officialDocs: [{ title: 'JSX로 마크업 작성하기', url: 'https://ko.react.dev/learn/writing-markup-with-jsx' }],
    tags: ['jsx'],
    prerequisites: ['first-component'],
  },
  {
    id: 'props',
    slug: 'props',
    title: 'Props로 데이터 전달하기',
    section: 'UI 표현하기',
    order: 4,
    level: 'beginner',
    estimatedMinutes: 18,
    summary: '부모 컴포넌트가 자식 컴포넌트에 읽기 전용 데이터를 전달합니다.',
    objectives: ['props를 전달할 수 있다.', 'props가 읽기 전용임을 이해한다.'],
    body: ['Props는 컴포넌트에 전달되는 입력값입니다.', '같은 컴포넌트를 다른 데이터로 여러 번 재사용할 수 있습니다.'],
    officialDocs: [{ title: '컴포넌트에 Props 전달하기', url: 'https://ko.react.dev/learn/passing-props-to-a-component' }],
    tags: ['props'],
    prerequisites: ['jsx-basics'],
  },
  {
    id: 'conditional-rendering',
    slug: 'conditional-rendering',
    title: '조건부 렌더링',
    section: 'UI 표현하기',
    order: 5,
    level: 'beginner',
    estimatedMinutes: 15,
    summary: '조건에 따라 다른 UI를 보여줍니다.',
    objectives: ['if, &&, 삼항 연산자로 UI를 분기할 수 있다.'],
    body: ['조건부 렌더링은 현재 상태나 props에 따라 다른 JSX를 반환하는 방법입니다.'],
    officialDocs: [{ title: '조건부 렌더링', url: 'https://ko.react.dev/learn/conditional-rendering' }],
    tags: ['conditional-rendering'],
    prerequisites: ['props'],
  },
  {
    id: 'rendering-lists',
    slug: 'rendering-lists',
    title: '리스트 렌더링과 key',
    section: 'UI 표현하기',
    order: 6,
    level: 'beginner',
    estimatedMinutes: 18,
    summary: '배열을 JSX 목록으로 바꾸고 key의 역할을 이해합니다.',
    objectives: ['map으로 목록을 렌더링할 수 있다.', 'key가 필요한 이유를 설명할 수 있다.'],
    body: ['React는 key를 사용해 목록 항목의 정체성을 추적합니다.'],
    officialDocs: [{ title: '리스트 렌더링', url: 'https://ko.react.dev/learn/rendering-lists' }],
    tags: ['lists', 'key'],
    prerequisites: ['conditional-rendering'],
  },
  {
    id: 'events',
    slug: 'events',
    title: '이벤트 처리',
    section: '상호작용 추가하기',
    order: 7,
    level: 'beginner',
    estimatedMinutes: 15,
    summary: '사용자 입력에 반응하는 이벤트 핸들러를 작성합니다.',
    objectives: ['클릭 이벤트를 처리할 수 있다.', '이벤트 핸들러를 props로 전달할 수 있다.'],
    body: ['이벤트 핸들러는 사용자의 행동에 반응하는 함수입니다.'],
    officialDocs: [{ title: '이벤트에 응답하기', url: 'https://ko.react.dev/learn/responding-to-events' }],
    tags: ['events'],
    prerequisites: ['rendering-lists'],
  },
  {
    id: 'state-usestate',
    slug: 'state-usestate',
    title: 'State와 useState',
    section: '상호작용 추가하기',
    order: 8,
    level: 'beginner',
    estimatedMinutes: 20,
    summary: '컴포넌트가 값을 기억하고 다시 렌더링하도록 state를 사용합니다.',
    objectives: ['state가 왜 필요한지 설명할 수 있다.', 'useState로 UI를 업데이트할 수 있다.', '일반 변수와 state의 차이를 이해한다.'],
    body: ['컴포넌트는 화면에 보여줄 값을 기억해야 할 때가 있습니다.', '일반 변수는 렌더링을 트리거하지 않지만 state는 값을 기억하고 React에게 다시 렌더링하라고 알려줍니다.'],
    officialDocs: [{ title: 'State: 컴포넌트의 기억', url: 'https://ko.react.dev/learn/state-a-components-memory' }],
    tags: ['state', 'useState'],
    prerequisites: ['events'],
  },
  {
    id: 'state-objects-arrays',
    slug: 'state-objects-arrays',
    title: '객체/배열 State 업데이트',
    section: '상호작용 추가하기',
    order: 9,
    level: 'beginner',
    estimatedMinutes: 25,
    summary: '객체와 배열 state를 직접 변경하지 않고 새 값으로 교체합니다.',
    objectives: ['state mutation을 피할 수 있다.', 'spread syntax로 새 객체/배열을 만들 수 있다.'],
    body: ['React state는 직접 수정하지 말고 새 객체나 배열로 교체해야 합니다.'],
    officialDocs: [
      { title: '객체 State 업데이트', url: 'https://ko.react.dev/learn/updating-objects-in-state' },
      { title: '배열 State 업데이트', url: 'https://ko.react.dev/learn/updating-arrays-in-state' },
    ],
    tags: ['state', 'immutability'],
    prerequisites: ['state-usestate'],
  },
  {
    id: 'thinking-in-react',
    slug: 'thinking-in-react',
    title: 'Thinking in React 입문',
    section: 'State 관리하기',
    order: 10,
    level: 'beginner',
    estimatedMinutes: 30,
    summary: 'UI를 컴포넌트 계층으로 나누고 최소 state를 찾습니다.',
    objectives: ['컴포넌트 계층을 설계할 수 있다.', '최소 state와 state 위치를 찾을 수 있다.'],
    body: ['Thinking in React는 UI를 컴포넌트로 나누고 데이터 흐름을 설계하는 공식 문서의 핵심 사고법입니다.'],
    officialDocs: [{ title: 'React로 사고하기', url: 'https://ko.react.dev/learn/thinking-in-react' }],
    tags: ['thinking-in-react', 'state-design'],
    prerequisites: ['state-objects-arrays'],
  },
]

export function getLessonBySlug(slug: string) {
  return lessons.find((lesson) => lesson.slug === slug)
}

export function getLessonById(id: string) {
  return lessons.find((lesson) => lesson.id === id)
}

export function lessonsBySection() {
  return lessons.reduce<Record<string, Lesson[]>>((groups, lesson) => {
    groups[lesson.section] = [...(groups[lesson.section] ?? []), lesson]
    return groups
  }, {})
}
